### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by kenorb** [vladcalin/eventer#1]
There is a problem installing [Quartz package](https://pypi.python.org/pypi/quartz)  from PyPI repository.

Here is the error:

```
$ pip3 install Quartz
Collecting Quartz
  Using cached quartz-0.0.1.dev0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/vp/tlt7xf791gl1_v56m0xdmrph0000gn/T/pip-build-7gmm18c9/Quartz/setup.py", line 35, in <module>
        install_requires=read_dependencies("requirements.txt"),
      File "/private/var/folders/vp/tlt7xf791gl1_v56m0xdmrph0000gn/T/pip-build-7gmm18c9/Quartz/setup.py", line 7, in read_dependencies
        with open(req_file) as req:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/vp/tlt7xf791gl1_v56m0xdmrph0000gn/T/pip-build-7gmm18c9/Quartz/
```

See also this post: [“No such file: 'requirements.txt' error” while installing Quartz module](https://stackoverflow.com/q/42530309/55075) for more details. It has also the workaround.

Basically `setup.py` has invalid path to `requirements.txt`, I believe it should be:

    install_requires=read_dependencies("quartz.egg-info/requires.txt")

**Comment by vladcalin** [comment]
Hello,

To fix this problem, I have to include `requirements.txt` in `MANIFEST.in` so that the file will be shipped with the sources.

Unfortunately, I abandoned this project a while ago and I am currently working on a complete rewrite (this version had some really messed up architectural choices that made feature writing harder than in should've been and the only way I found to fix the poor architectural choices was to go for another architecture completely).

The other version is on Bitbucket on a private repository, and when it will be ready for the first public release, I will upload it on this repository.

Cheers!
